# Generated by Django 3.2.9 on 2021-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Emergency Medicine', 'Emergency Medicine '), ('Allergy', 'Allergy'), ('Opthamology', 'Opthamology')], default='Cardiology', max_length=40),
        ),
    ]
