# Generated by Django 3.2.9 on 2021-11-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='mobile',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/'),
        ),
    ]
